try:
    from importlib.metadata import version as _pkg_version
    __version__ = _pkg_version("shipit-agent")
except Exception:
    __version__ = "0.0.0+unknown"

from .async_runtime import AsyncAgentRuntime
from .deep import AdaptiveAgent, AgentBenchmark, AgentMessage, BenchmarkReport, Channel, Checkpoint, Goal, GoalAgent, GoalResult, PersistentAgent, ReflectionResult, ReflectiveAgent, Supervisor, SupervisorResult, TestCase, Worker
from .exceptions import DuplicateToolError, ShipitAgentError
from .hooks import AgentHooks
from .memory import AgentMemory, ConversationMemory, Entity, EntityMemory, InMemoryVectorStore, SearchResult, SemanticMemory, VectorStore
from .parsers import JSONParser, MarkdownParser, MarkdownResult, OutputParser, ParseError, PydanticParser, RegexParser
from .pipeline import Pipeline, Step, parallel, step
from .structured import build_schema_prompt, is_pydantic_model, parse_structured_output, schema_to_response_format
from .team import AgentTeam, TeamAgent, TeamResult, TeamRound
from .agent import Agent
from .builtins import get_builtin_tools
from .chat_session import AgentChatSession
from .construction import build_tool_schemas, construct_tool_registry
from .doctor import AgentDoctor, DoctorCheck, DoctorReport
from .integrations import CredentialRecord, CredentialStore, FileCredentialStore, FileOAuthStateStore, GoogleOAuthHelper, InMemoryCredentialStore, InMemoryOAuthStateStore, OAuthClientConfig, OAuthHelper, OAuthStateStore, SlackOAuthHelper
from .mcp import MCPError, MCPHTTPTransport, MCPServer, MCPSubprocessTransport, MCPTool, PersistentMCPSubprocessTransport, RemoteMCPServer, discover_mcp_tools
from .models import AgentEvent, AgentResult, Artifact, Message, ToolCall, ToolResult
from .packets import event_packet, result_packet, sse_event_packet, sse_result_packet, websocket_event_packet, websocket_result_packet
from .policies import RetryPolicy, RouterPolicy
from .profiles import AgentProfile, AgentProfileBuilder
from .prompts.default_agent_prompt import DEFAULT_AGENT_PROMPT
from .reasoning import ReasoningResult, ReasoningRuntime
from .registry import ToolRegistry
from .stores import FileMemoryStore, FileSessionStore, InMemoryMemoryStore, InMemorySessionStore, MemoryFact, MemoryStore, SessionRecord, SessionStore
from .tool_runner import ToolRunner, ToolRunnerResult
from .tracing import FileTraceStore, InMemoryTraceStore, TraceRecord, TraceStore
from .tools import (
    AskUserTool,
    ArtifactBuilderTool,
    BraveSearchProvider,
    build_search_provider,
    CodeExecutionTool,
    ConfluenceTool,
    CustomAPITool,
    DecisionMatrixTool,
    DuckDuckGoSearchProvider,
    EvidenceSynthesisTool,
    FunctionTool,
    GmailTool,
    GoogleCalendarTool,
    GoogleDriveTool,
    HumanReviewTool,
    JiraTool,
    LinearTool,
    MemoryTool,
    NotionTool,
    OpenURLTool,
    PlaywrightBrowserTool,
    PlaywrightSearchProvider,
    PlannerTool,
    PromptTool,
    SerperSearchProvider,
    SlackTool,
    SubAgentTool,
    TavilySearchProvider,
    ThoughtDecompositionTool,
    Tool,
    ToolSearchTool,
    ToolContext,
    ToolOutput,
    VerifierTool,
    WebSearchTool,
    WorkspaceFilesTool,
)

__all__ = [
    "AdaptiveAgent",
    "Agent",
    "AgentBenchmark",
    "AgentChatSession",
    "AgentHooks",
    "AgentMemory",
    "AgentMessage",
    "AgentTeam",
    "AsyncAgentRuntime",
    "BenchmarkReport",
    "Channel",
    "Checkpoint",
    "ConversationMemory",
    "Entity",
    "EntityMemory",
    "Goal",
    "GoalAgent",
    "GoalResult",
    "InMemoryVectorStore",
    "JSONParser",
    "MarkdownParser",
    "MarkdownResult",
    "OutputParser",
    "ParseError",
    "PersistentAgent",
    "Pipeline",
    "PydanticParser",
    "ReflectionResult",
    "ReflectiveAgent",
    "RegexParser",
    "SearchResult",
    "SemanticMemory",
    "Step",
    "Supervisor",
    "SupervisorResult",
    "TeamAgent",
    "TeamResult",
    "TeamRound",
    "TestCase",
    "VectorStore",
    "Worker",
    "build_schema_prompt",
    "is_pydantic_model",
    "parallel",
    "parse_structured_output",
    "schema_to_response_format",
    "step",
    "event_packet",
    "AgentEvent",
    "ReasoningResult",
    "ReasoningRuntime",
    "AgentProfile",
    "AgentProfileBuilder",
    "AgentResult",
    "AskUserTool",
    "Artifact",
    "ArtifactBuilderTool",
    "build_tool_schemas",
    "construct_tool_registry",
    "BraveSearchProvider",
    "CodeExecutionTool",
    "ConfluenceTool",
    "CredentialRecord",
    "CredentialStore",
    "CustomAPITool",
    "DEFAULT_AGENT_PROMPT",
    "DecisionMatrixTool",
    "DoctorCheck",
    "DoctorReport",
    "discover_mcp_tools",
    "get_builtin_tools",
    "AgentDoctor",
    "build_search_provider",
    "DuplicateToolError",
    "DuckDuckGoSearchProvider",
    "EvidenceSynthesisTool",
    "FileMemoryStore",
    "FileSessionStore",
    "FunctionTool",
    "FileCredentialStore",
    "FileOAuthStateStore",
    "FileTraceStore",
    "GmailTool",
    "GoogleOAuthHelper",
    "GoogleCalendarTool",
    "GoogleDriveTool",
    "HumanReviewTool",
    "InMemoryMemoryStore",
    "InMemoryCredentialStore",
    "InMemoryOAuthStateStore",
    "InMemorySessionStore",
    "InMemoryTraceStore",
    "JiraTool",
    "LinearTool",
    "MCPError",
    "MCPHTTPTransport",
    "MCPServer",
    "MCPSubprocessTransport",
    "MCPTool",
    "PersistentMCPSubprocessTransport",
    "MemoryTool",
    "MemoryFact",
    "MemoryStore",
    "Message",
    "OpenURLTool",
    "OAuthClientConfig",
    "OAuthHelper",
    "OAuthStateStore",
    "PlaywrightBrowserTool",
    "PlaywrightSearchProvider",
    "PlannerTool",
    "PromptTool",
    "RemoteMCPServer",
    "result_packet",
    "RetryPolicy",
    "RouterPolicy",
    "sse_event_packet",
    "sse_result_packet",
    "SerperSearchProvider",
    "SessionRecord",
    "SessionStore",
    "ShipitAgentError",
    "SlackOAuthHelper",
    "SlackTool",
    "SubAgentTool",
    "TavilySearchProvider",
    "ThoughtDecompositionTool",
    "Tool",
    "ToolRunner",
    "ToolRunnerResult",
    "ToolRegistry",
    "TraceRecord",
    "TraceStore",
    "ToolSearchTool",
    "ToolCall",
    "ToolContext",
    "ToolOutput",
    "ToolResult",
    "VerifierTool",
    "WebSearchTool",
    "websocket_event_packet",
    "websocket_result_packet",
    "WorkspaceFilesTool",
]
