try:
    from importlib.metadata import version as _pkg_version

    __version__ = _pkg_version("shipit-agent")
except Exception:
    __version__ = "0.0.0+unknown"

from .async_runtime import AsyncAgentRuntime
from .deep import (
    AdaptiveAgent,
    AgentBenchmark,
    AgentMessage,
    BenchmarkReport,
    Channel,
    Checkpoint,
    DEEP_AGENT_PROMPT,
    DeepAgent,
    Goal,
    GoalAgent,
    GoalResult,
    PersistentAgent,
    ReflectionResult,
    ReflectiveAgent,
    Supervisor,
    SupervisorResult,
    TestCase,
    Worker,
    create_deep_agent,
)
from .exceptions import DuplicateToolError, ShipitAgentError
from .hooks import AgentHooks
from .memory import (
    AgentMemory,
    ConsolidationResult,
    ConversationMemory,
    DistilledFact,
    Entity,
    EntityMemory,
    InMemoryVectorStore,
    MemoryConsolidator,
    SearchResult,
    SemanticMemory,
    VectorStore,
)
from .parsers import (
    JSONParser,
    MarkdownParser,
    MarkdownResult,
    OutputParser,
    ParseError,
    PydanticParser,
    RegexParser,
    parse_partial_json,
)
from .pipeline import Pipeline, Step, parallel, step
from .structured import (
    build_schema_prompt,
    is_pydantic_model,
    parse_structured_output,
    schema_to_response_format,
)
from .structured_output import StructuredOutput, StructuredOutputResult
from .computer_use import (
    ActionKind,
    ActionRecord,
    BrowserSession,
    ComputerAction,
    ComputerUseAgent,
    ComputerUseResult,
    MockBrowserSession,
    PlaywrightBrowserSession,
    parse_action,
)
from .multimodal import (
    FileMediaStore,
    InMemoryMediaStore,
    MediaKind,
    MediaParser,
    MediaReference,
    MediaStore,
    ParsedPrompt,
    StoredMedia,
    build_multimodal_message,
    extract_media_refs,
)
from .replay import (
    ForkPoint,
    ReplayCheckpoint,
    ReplayResult,
    TraceDiff,
    TraceReplayer,
    diff_traces,
)
from .verifier import (
    PreToolDecision,
    PreToolVerifier,
    ProgressCheck,
    ProgressVerifier,
    VerifierConfig,
    VerifierNetwork,
    VerifierVerdict,
)
from .team import AgentTeam, TeamAgent, TeamResult, TeamRound
from .activity import StreamRenderer, format_activity, format_event_line
from .approvals import ActionState, ApprovalQueue, PendingAction
from .compaction import CompactionCheckpoint, Compactor, get_model_limits
from .token_calibration import TokenCalibrator
from .connections import (
    AuthKind,
    Connection,
    ConnectionRegistry,
    ConnectionState,
)
from .lockdown import LockdownPolicy, LockdownState
from .streaming import STREAM_GENERATION, Durability, StreamFrame, classify, sse
from .triggers import (
    InMemoryTriggerQueue,
    SqliteTriggerQueue,
    Trigger,
    TriggerEvent,
    TriggerRegistry,
    TriggerRun,
    fire_all,
)
from .delegation import DelegationAdvice, DelegationPolicy
from .narrate import (
    NarratorRenderer,
    build_transcript,
    render_transcript,
    render_transcript_html,
    render_tree,
    summarize,
    write_transcript,
)
from .narrate.json_stream import StreamingToolInputParser

# `ActionKind` is already public from .computer_use — alias rather than shadow it.
from .tools.contracts import ActionKind as ToolActionKind
from .tools.contracts import ToolContract, contract_for
from .guardrails import GuardDecision, Guardrails
from .hitl import console_permission_prompt, format_call_preview
from .agent import Agent, DEFAULT_SKILLS_PATH
from .builtins import get_builtin_tool_map, get_builtin_tools
from .chat_session import AgentChatSession
from .construction import build_tool_schemas, construct_tool_registry
from .context_tracker import ContextSnapshot, ContextTracker
from .doctor import AgentDoctor, DoctorCheck, DoctorReport
from .integrations import (
    CredentialRecord,
    CredentialStore,
    FileCredentialStore,
    FileOAuthStateStore,
    GoogleOAuthHelper,
    InMemoryCredentialStore,
    InMemoryOAuthStateStore,
    OAuthClientConfig,
    OAuthHelper,
    OAuthStateStore,
    SlackOAuthHelper,
)
from .mcp import (
    MCPError,
    MCPHTTPTransport,
    MCPPrompt,
    MCPResource,
    MCPServer,
    MCPStdioTransport,
    MCPStreamableHTTPTransport,
    MCPSubprocessTransport,
    MCPTool,
    PersistentMCPSession,
    PersistentMCPSubprocessTransport,
    RemoteMCPServer,
    discover_mcp_tools,
)
from .connectors import (
    Connector,
    connect,
    connector_categories,
    list_connectors,
)
from .mcp_catalog import (
    MCP_CATALOG,
    MCPCatalogEntry,
    connect_mcp,
    list_mcp_catalog,
)
from .models import AgentEvent, AgentResult, Artifact, Message, ToolCall, ToolResult
from .packets import (
    event_packet,
    result_packet,
    sse_event_packet,
    sse_result_packet,
    websocket_event_packet,
    websocket_result_packet,
)
from .permissions import (
    PermissionDecision,
    PermissionEngine,
    PermissionResult,
)
from .workspace import (
    WorkspaceSettings,
    discover_commands,
    expand_command,
    load_project_memory,
    load_settings,
)
from .policies import RetryPolicy, RouterPolicy
from .profiles import AgentProfile, AgentProfileBuilder
from .prompts.default_agent_prompt import DEFAULT_AGENT_PROMPT
from .reasoning import ReasoningResult, ReasoningRuntime
from .registry import ToolRegistry
from .schedule import (
    AgentScheduler,
    ScheduledAgentConfig,
    ScheduledAgentFactory,
    ScheduledJob,
    ScheduleResult,
    ScheduleRunner,
    SQLiteJobStore,
)
from .session_manager import SessionManager
from .stores import (
    FileMemoryStore,
    FileSessionStore,
    InMemoryMemoryStore,
    InMemorySessionStore,
    MemoryFact,
    MemoryStore,
    SessionRecord,
    SessionStore,
)
from .templates import PromptTemplate
from .tool_runner import ToolRunner, ToolRunnerResult
from .tracing import FileTraceStore, InMemoryTraceStore, TraceRecord, TraceStore
from .skills import (
    FileSkillRegistry,
    SkillCatalog,
    Skill,
    SkillRegistry,
    discover_project_skills,
    load_markdown_skill,
    apply_skill,
    create_skill,
    find_relevant_skills,
    match_skill_by_trigger,
    skill_id_from_name,
)
from .rag import (
    Chunk as RAGChunk,
    Document as RAGDocument,
    IndexFilters as RAGIndexFilters,
    RAGContext,
    RAGSource,
    SearchQuery as RAGSearchQuery,
    SearchResult as RAGSearchResult,
)
from .rag.rag import RAG
from .rag.chunker import DocumentChunker
from .rag.embedder import CallableEmbedder, HashingEmbedder
from .rag.reranker import LLMReranker
from .rag.search_pipeline import HybridSearchPipeline
from .notifications import (
    DiscordNotifier,
    Notification,
    NotificationManager,
    Notifier,
    SlackNotifier,
    TelegramNotifier,
)
from .costs import (
    Budget,
    BudgetExceededError,
    CostRecord,
    CostTracker,
    MODEL_ALIASES,
    MODEL_PRICING,
)
from .batch import (
    BatchRequest,
    BatchResult,
    BatchRuntime,
    MessageBatchRunner,
)
from .tools import (
    AgentTool,
    AskUserTool,
    ArtifactBuilderTool,
    DeepResearchTool,
    DocumentBuilderTool,
    DownloadFileTool,
    BashTool,
    BraveSearchProvider,
    build_search_provider,
    ClaudeMemoryTool,
    CodeExecutionTool,
    ConfluenceTool,
    CustomAPITool,
    DecisionMatrixTool,
    DuckDuckGoSearchProvider,
    EditFileTool,
    EvidenceSynthesisTool,
    FileReadTool,
    FileWriteTool,
    FunctionTool,
    FigmaTool,
    GitHubTool,
    GitOpsTool,
    GitLabTool,
    GmailTool,
    GlobSearchTool,
    GoogleCalendarTool,
    GoogleDriveTool,
    GoogleSheetsTool,
    GrepSearchTool,
    HumanReviewTool,
    JiraTool,
    LinearTool,
    LinkedInSearchTool,
    MemoryTool,
    NotebookEditTool,
    NotionTool,
    OpenURLTool,
    PDFTool,
    PlaywrightBrowserTool,
    PlaywrightSearchProvider,
    PlannerTool,
    PromptTool,
    SalesforceTool,
    SerperSearchProvider,
    SlackTool,
    SQLTool,
    StripeTool,
    SubAgentTool,
    TavilySearchProvider,
    ThoughtDecompositionTool,
    TodoTool,
    Tool,
    ToolSearchTool,
    ToolContext,
    ToolOutput,
    ToolOutputChunk,
    ToolRunOutput,
    VerifierTool,
    VisionTool,
    WebSearchTool,
    WebhookPayloadTool,
    WorkspaceFilesTool,
    ZendeskTool,
)

__all__ = [
    "AdaptiveAgent",
    "Agent",
    "DEFAULT_SKILLS_PATH",
    "AgentBenchmark",
    "AgentChatSession",
    "AgentHooks",
    "AgentMemory",
    "AgentMessage",
    "AgentTeam",
    "AsyncAgentRuntime",
    "BenchmarkReport",
    "Channel",
    "Checkpoint",
    "ConsolidationResult",
    "ConversationMemory",
    "DistilledFact",
    "MemoryConsolidator",
    "DEEP_AGENT_PROMPT",
    "DeepAgent",
    "create_deep_agent",
    "Entity",
    "EntityMemory",
    "Goal",
    "GoalAgent",
    "GoalResult",
    "InMemoryVectorStore",
    "JSONParser",
    "MarkdownParser",
    "MarkdownResult",
    "OutputParser",
    "ParseError",
    "PersistentAgent",
    "Pipeline",
    "PydanticParser",
    "ReflectionResult",
    "ReflectiveAgent",
    "RegexParser",
    "SearchResult",
    "AgentScheduler",
    "ScheduledJob",
    "ScheduledAgentConfig",
    "ScheduledAgentFactory",
    "ScheduleResult",
    "ScheduleRunner",
    "SQLiteJobStore",
    "ActionState",
    "ApprovalQueue",
    "CompactionCheckpoint",
    "AuthKind",
    "Connection",
    "ConnectionRegistry",
    "ConnectionState",
    "Durability",
    "LockdownPolicy",
    "STREAM_GENERATION",
    "StreamFrame",
    "classify",
    "sse",
    "LockdownState",
    "Compactor",
    "TokenCalibrator",
    "StreamingToolInputParser",
    "get_model_limits",
    "NarratorRenderer",
    "PendingAction",
    "ToolActionKind",
    "ToolContract",
    "contract_for",
    "StreamRenderer",
    "Trigger",
    "TriggerEvent",
    "TriggerRegistry",
    "SqliteTriggerQueue",
    "InMemoryTriggerQueue",
    "fire_all",
    "DelegationPolicy",
    "DelegationAdvice",
    "TriggerRun",
    "build_transcript",
    "render_transcript",
    "render_transcript_html",
    "render_tree",
    "write_transcript",
    "summarize",
    "SemanticMemory",
    "Step",
    "Supervisor",
    "SupervisorResult",
    "TeamAgent",
    "TeamResult",
    "TeamRound",
    "TestCase",
    "VectorStore",
    "Worker",
    "ActionKind",
    "ActionRecord",
    "BrowserSession",
    "ComputerAction",
    "ComputerUseAgent",
    "ComputerUseResult",
    "FileMediaStore",
    "ForkPoint",
    "InMemoryMediaStore",
    "MediaKind",
    "MediaParser",
    "MediaReference",
    "MediaStore",
    "MockBrowserSession",
    "ParsedPrompt",
    "PlaywrightBrowserSession",
    "StoredMedia",
    "build_multimodal_message",
    "extract_media_refs",
    "parse_action",
    "PreToolDecision",
    "PreToolVerifier",
    "ProgressCheck",
    "ProgressVerifier",
    "ReplayCheckpoint",
    "ReplayResult",
    "TraceDiff",
    "TraceReplayer",
    "diff_traces",
    "StructuredOutput",
    "StructuredOutputResult",
    "VerifierConfig",
    "VerifierNetwork",
    "VerifierVerdict",
    "build_schema_prompt",
    "is_pydantic_model",
    "parallel",
    "parse_partial_json",
    "parse_structured_output",
    "schema_to_response_format",
    "step",
    "event_packet",
    "AgentEvent",
    "ReasoningResult",
    "ReasoningRuntime",
    "AgentProfile",
    "AgentProfileBuilder",
    "AgentResult",
    "AgentTool",
    "AskUserTool",
    "Artifact",
    "ArtifactBuilderTool",
    "DeepResearchTool",
    "DocumentBuilderTool",
    "DownloadFileTool",
    "BashTool",
    "build_tool_schemas",
    "construct_tool_registry",
    "BraveSearchProvider",
    "ClaudeMemoryTool",
    "CodeExecutionTool",
    "ConfluenceTool",
    "ContextSnapshot",
    "ContextTracker",
    "CredentialRecord",
    "CredentialStore",
    "CustomAPITool",
    "DEFAULT_AGENT_PROMPT",
    "DecisionMatrixTool",
    "DoctorCheck",
    "DoctorReport",
    "discover_mcp_tools",
    "discover_project_skills",
    "get_builtin_tool_map",
    "get_builtin_tools",
    "AgentDoctor",
    "build_search_provider",
    "DuplicateToolError",
    "DuckDuckGoSearchProvider",
    "EditFileTool",
    "EvidenceSynthesisTool",
    "FileReadTool",
    "FileWriteTool",
    "FileMemoryStore",
    "FileSessionStore",
    "FunctionTool",
    "FigmaTool",
    "FileCredentialStore",
    "FileOAuthStateStore",
    "FileTraceStore",
    "format_activity",
    "format_event_line",
    "GuardDecision",
    "Guardrails",
    "console_permission_prompt",
    "format_call_preview",
    "GitHubTool",
    "GitOpsTool",
    "GitLabTool",
    "GmailTool",
    "GlobSearchTool",
    "GoogleOAuthHelper",
    "GoogleCalendarTool",
    "GoogleDriveTool",
    "GoogleSheetsTool",
    "GrepSearchTool",
    "HumanReviewTool",
    "InMemoryMemoryStore",
    "InMemoryCredentialStore",
    "InMemoryOAuthStateStore",
    "InMemorySessionStore",
    "InMemoryTraceStore",
    "JiraTool",
    "LinearTool",
    "LinkedInSearchTool",
    "MCPError",
    "MCPHTTPTransport",
    "MCPPrompt",
    "MCPResource",
    "MCPServer",
    "MCPStdioTransport",
    "MCPStreamableHTTPTransport",
    "MCPSubprocessTransport",
    "MCPTool",
    "MCP_CATALOG",
    "MCPCatalogEntry",
    "Connector",
    "connect",
    "connect_mcp",
    "connector_categories",
    "list_connectors",
    "list_mcp_catalog",
    "PersistentMCPSession",
    "PersistentMCPSubprocessTransport",
    "MemoryTool",
    "MemoryFact",
    "MemoryStore",
    "Message",
    "NotebookEditTool",
    "NotionTool",
    "OpenURLTool",
    "OAuthClientConfig",
    "OAuthHelper",
    "OAuthStateStore",
    "PDFTool",
    "PlaywrightBrowserTool",
    "PlaywrightSearchProvider",
    "PlannerTool",
    "PromptTool",
    "PromptTemplate",
    "RemoteMCPServer",
    "result_packet",
    "PermissionDecision",
    "PermissionEngine",
    "PermissionResult",
    "WorkspaceSettings",
    "load_project_memory",
    "load_markdown_skill",
    "load_settings",
    "discover_commands",
    "expand_command",
    "RetryPolicy",
    "RouterPolicy",
    "SalesforceTool",
    "sse_event_packet",
    "sse_result_packet",
    "SerperSearchProvider",
    "SessionManager",
    "SessionRecord",
    "SessionStore",
    "ShipitAgentError",
    "SlackOAuthHelper",
    "SlackTool",
    "SQLTool",
    "StripeTool",
    "SubAgentTool",
    "TavilySearchProvider",
    "ThoughtDecompositionTool",
    "TodoTool",
    "Tool",
    "ToolRunner",
    "ToolRunnerResult",
    "ToolRegistry",
    "TraceRecord",
    "TraceStore",
    "ToolSearchTool",
    "ToolCall",
    "ToolContext",
    "ToolOutput",
    "ToolOutputChunk",
    "ToolRunOutput",
    "ToolResult",
    "VerifierTool",
    "VisionTool",
    "WebSearchTool",
    "WebhookPayloadTool",
    "websocket_event_packet",
    "websocket_result_packet",
    "WorkspaceFilesTool",
    "ZendeskTool",
    # --- Skills subsystem -----------------------------------------------------
    "FileSkillRegistry",
    "SkillCatalog",
    "Skill",
    "SkillRegistry",
    "apply_skill",
    "create_skill",
    "find_relevant_skills",
    "match_skill_by_trigger",
    "skill_id_from_name",
    # --- Super RAG subsystem ------------------------------------------------
    "RAG",
    "RAGChunk",
    "RAGContext",
    "RAGDocument",
    "RAGIndexFilters",
    "RAGSearchQuery",
    "RAGSearchResult",
    "RAGSource",
    "DocumentChunker",
    "HybridSearchPipeline",
    "HashingEmbedder",
    "CallableEmbedder",
    "LLMReranker",
    # --- Notification Hub -------------------------------------------------
    "DiscordNotifier",
    "Notification",
    "NotificationManager",
    "Notifier",
    "SlackNotifier",
    "TelegramNotifier",
    # --- Cost Tracking & Budgets ------------------------------------------
    "Budget",
    "BudgetExceededError",
    "CostRecord",
    "CostTracker",
    "MODEL_ALIASES",
    "MODEL_PRICING",
    # --- Batch API runtime (bulk/offline, ~50% cost) ----------------------
    "BatchRequest",
    "BatchResult",
    "BatchRuntime",
    "MessageBatchRunner",
]
